apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-list
spec:
  replicas: 3
  selector:
    matchLabels:
      app: to-do-list
  template:
    metadata:
      labels:
        app: to-do-list
    spec:
      containers:
        - name: to-do-list
          image: avibhatnagar/to-do-list
          ports:
            - containerPort: 3000
